//export const ADD_PLACE = 'ADD_PLACE';
//export const DELETE_PLACE = 'DELETE_PLACE';

export const TRY_AUTH = 'TRY_AUTH';
// Logging User
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const EXPIRED_TOKEN = 'EXPIRED_TOKEN';

// Structure Create Edit Delete
export const CREATE_STRUCTURE = 'CREATE_STRUCTURE';
export const CREATE_STRUCTURE_SUCCESS = 'CREATE_STRUCTURE_SUCCESS';
export const CREATE_STRUCTURE_FAILURE = 'CREATE_STRUCTURE_FAILURE';
export const EDIT_STRUCTURE = 'EDIT_STRUCTURE';
export const EDIT_STRUCTURE_SUCCESS = 'EDIT_STRUCTURE_SUCCESS';
export const EDIT_STRUCTURE_FAILURE = 'EDIT_STRUCTURE_FAILURE';
export const DELETE_STRUCTURE = 'DELETE_STRUCTURE';
export const DELETE_STRUCTURE_SUCCESS = 'DELETE_STRUCTURE_SUCCESS';
export const DELETE_STRUCTURE_FAILURE = 'DELETE_STRUCTURE_FAILURE';


